apiVersion: v1
kind: Namespace
metadata:
  name: otel
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: opentelemetry-operator
  namespace: otel
spec:
  channel: stable
  installPlanApproval: Automatic
  name: opentelemetry-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
