---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kbot
  namespace: monitoring
spec:
  encryptedData:
    token: AgAfgv2T0Q7gJpUXBu1+nDZw818YzgzoATPBPtrwAyNjYkB3zYyovVlI9XLkLZKL/HVY+LY4VO68XOEhRqnwQU8OrtZks54GUtTkT9NUftks1yXNFz3/Ypab/ipAxXJqz/mQuoaovdYbhB9NFWZpQDoyqRMnyoADMalnrPHSfrkQWLKWLajvs7xcbnn1Ht1C5Pnh7zCbwLngXyaT9XOWGb19y0G8eD3ho2+Y8+34b5ZCjd8WdNrLoZGIgVswB2/DIP3DnV5+e6TB0HzIk+NYONDuZNO3ZVo/L0VYelAAhJSeXoVcCxUPFZq7Fh5ORAx0b4JdL4IYhmQH7EOuPnA3qmbIRbWjeJP0UhvCgHqNMD2+5e7WhmaLpCvosR4qOU6w+pjFjhTbeWlRAIUfFqYbcuEEaZEpbj4guyMPZqrE6iW2YNr1p0iSx+/5mo3XV6uh9cz+AeDsbFEOPHeXQboEfL6cG37IWanLceQE+9ldh+NLMveQ4uMyxs310dTobjD2aAjyKiTaKxe1e2hkquIY8hc15GkN3hmUX89RUNdmJCLeex2NIjHpBkC5LjIWvbg6cX8uOVch3UQh/Z3woFL5vQ4MSzoKM2vvwosaBpRE4UgQMendURIqSh2Fq8zX71mMKxxxGsoUyjerKbJkmdoUukfjSYkobRzQ2dlBpRZmGDd4N6QOlbPvHFRspzV5Ln639sAUm1A0ijnAzQt6hRFNqGESoiqfMFa7x3pw/IbjL3mwxQQz3gYR7AtwAAOclUGv
  template:
    metadata:
      creationTimestamp: null
      name: kbot
      namespace: monitoring
