---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  interval: 1m0s
  url: https://fluent.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  chart:
    spec:
      chart: fluent/fluent-bit
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: fluent-bit
        namespace: monitoring
  interval: 1m0s 
