apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: monitoring
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        Off
        Parsers_File  parsers.conf

    [INPUT]
        Name              tail
        Path              /var/log/containers/*.log
        Parser            docker
        Tag               kube.*

    [OUTPUT]
        Name              loki
        Match             *
        url               http://loki:3100/loki/api/v1/push
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-input
  namespace: monitoring
data:
  parsers.conf: |
    [PARSER]
        Name   docker
        Format regex
        Regex  ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>.[^ ]*) (?<log>.*)$
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:1.11
        env:
          - name: FLUENT_BIT_CONF
            value: /fluent-bit/etc/fluent-bit.conf
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config
